server:
  port: 8080
  error:
    include-message: always
  servlet:
    context-path: /parcel-notification-service

novaposhta-api:
  base-url: ${API_BASE_URL:https://api.novaposhta.ua/v2.0/json/}
  api-key: ${API_KEY:}
  sender-phone-number: ${SENDER_PHONE_NUMBER:}
  return-order:
    recipient-settlement: ${RECIPIENT_SETTELEMENT:}
    recipient-settlement-street: ${RECIPIENT_SETTELEMENT_STREET:}
    building-number: ${BUILDING_NUMBER:}
    return-reason: ${RETURN_REASON:}
    return-subtype-reason: ${RETURN_SUBTYPE_REASON:}

web.client:
  http-client-response-timeout: ${HTTP_CLIENT_RESPONSE_TIMEOUT:60}
  connection-provider-max-idle-time: ${CONNECTION_PROVIDER_MAX_IDLE_TIME:60}
  connection-provider-max-life-time: ${CONNECTION_PROVIDER_MAX_LIFE_TIME:120}
  connection-provider-pending-acquire-timeout: ${CONNECTION_PROVIDER_PENDING_ACQUIRE_TIMEOUT:60}
  connection-provider-evict-in-background-timeout: ${CONNECTION_PROVIDER_EVICT_IN_BACKGROUND_TIMEOUT:120}

csv:
  response-headers: ${CSV_EXPORT_RESPONSE_HEADERS:ЕН,ПІБ отримувача з накладної,Номер телефону отримувача,Місто отримувача,Фактична дата доставки,Сума зворотної доставки,Поточне значення суми грошового переказу,Вартість доставки,Дата початку платного зберігання,Сума оплати по ЕН,Дата повернення вантажу,Дата початку зберігання (після не отримання),Оголошена вартість,Вартість зберігання}
  response-fields: ${CSV_EXPORT_RESPONSE_FIELDS:Number,RecipientFullNameEW,PhoneRecipient,CityRecipient,ActualDeliveryDate,RedeliverySum,LastAmountTransferGM,DocumentCost,DatePayedKeeping,ExpressWaybillAmountToPay,DateReturnCargo,DateFirstDayStorage,AnnouncedPrice,StoragePrice}
  export-csv-limit: 500

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
    password: ${SMTP_PASSWORD:}
    username: ${SMTP_LOGIN:}

email-notification:
  recipient: ${EMAIL_RECIPIENT:}
  sender: ${EMAIL_SENDER:}
  not-received-parcels-subject: ${NOT_RECEIVED_PARCELS_EMAIL_SUBJECT:Not received parcels found!}
  not-received-parcels-message: ${NOT_RECEIVED_PARCELS_EMAIL_MESSAGE:This letter was generated automatically because were detected parcels that were waiting for the recipient at the post office for more than four days from the time of delivery.}
  returned-parcels-subject: ${RETURNED_PARCELS_EMAIL_SUBJECT:New parcel return request have been created!}
  returned-parcels-message: ${RETURNED_PARCELS_EMAIL_MESSAGE:This letter was generated automatically because a new parcel return request(s) was created for the following EN(s) :.}

scheduled:
  parcel-search-job: ${PARCEL_SEARCH_JOB:0 0 10 */2 * ?}
  parcel-return-order-job: ${PARCEL_RETURN_ORDER_JOB:0 0 11 * * ?}
  max-storage-days-before-return-order: ${MAX_STORAGE_DAYS_BEFORE_RETURN_ORDER:6}
  max-storage-days-before-notification: ${MAX_STORAGE_DAYS_BEFORE_NOTIFICATION:4}

telegram-bot:
  hookahcat-pns:
    bot-token: ${HOOKAH_CAT_PNS_TOKEN:}
    bot-username: ${HOOKAH_CAT_PNS_USERNAME:}